-- Inserts
INSERT INTO turno(turno, descr)
VALUES(1, 'MATUTINO'),
VALUES(2, 'VESPERTINO'),
VALUES(3, 'NOCTURNO'),
VALUES(4, 'ESPECIAL');

-- ATRIBUTOS
INSERT INTO atributo(atributo, descr)
VALUES(1, 'MADRE'),
VALUES(2, 'PADRE');

-- CONTROL
-- EJECUTAR CONSULTA PARA OBTENER DATOS

-- SEMANA
INSERT INTO semana(dia, descr)
VALUES(0, 'DOMINGO'),
VALUES(1, 'LUNES'),
VALUES(2, 'MARTES'),
VALUES(3, 'MIERCOLES'),
VALUES(4, 'JUEVES'),
VALUES(5, 'VIERNES'),
VALUES(6, 'SABADO');
